name: Flake

on: pull_request

permissions:
  id-token: "write"
  contents: "read"

jobs:
  lockfile-drv-changed:
    runs-on: ubuntu-24.04

    steps:
      - name: Check changed files
        id: changed
        run: |
          files=$(gh pr diff "$PR_NUMBER" --name-only)
          if [ "$files" = "flake.lock" ]; then
            echo "only_lock_changed=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "only_lock_changed=false" | tee -a "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - uses: DeterminateSystems/nix-installer-action@main
        if: steps.changed.outputs.only_lock_changed == 'true'

      - name: Get base SHA derivation path
        if: steps.changed.outputs.only_lock_changed == 'true'
        run: |
          set -o pipefail
          nix eval --json "$FLAKE_URI#packages" | jq >base.json
        env:
          FLAKE_URI: "github:${{ github.event.pull_request.base.repo.full_name }}/${{ github.event.pull_request.base.sha }}"

      - name: Get head SHA derivation path
        if: steps.changed.outputs.only_lock_changed == 'true'
        run: |
          set -o pipefail
          nix eval --json "$FLAKE_URI#packages" | jq >head.json
        env:
          FLAKE_URI: "github:${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.sha }}"

      - name: Compare head and base derivation paths
        if: steps.changed.outputs.only_lock_changed == 'true'
        run: |
          if cmp -s base.json head.json; then
            echo "::error file=flake.lock::flake.lock changes produced the same derivation output"
            exit 1
          else
            diff base.json head.json || true
          fi
