name: Flake

on: pull_request

permissions:
  id-token: "write"
  contents: "read"

jobs:
  lockfile-drv-changed:
    runs-on: ubuntu-24.04

    steps:
      - name: Check changed files
        id: changed
        run: |
          files=$(gh pr diff "$PR_NUMBER" --name-only)
          if [ "$files" = "flake.lock" ]; then
            echo "only_lock_changed=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "only_lock_changed=false" | tee -a "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Write all packages expression
        run: |
          echo "$NIX_EXPR" >all-packages.nix
        env:
          NIX_EXPR: |
            let
              flake = builtins.getFlake (builtins.getEnv "FLAKE_URI");
            in
            derivation {
              __structuredAttrs = true;
              name = "all-packages";
              system = "x86_64-linux";
              builder = "/bin/sh";
              inherit (flake.outputs) packages;
            }

      - name: Get base SHA derivation path
        id: base-drv
        if: steps.changed.outputs.only_lock_changed == 'true'
        run: |
          set -o pipefail
          echo -n "path=" >>"$GITHUB_OUTPUT"
          nix eval --raw --file ./all-packages.nix | tee -a "$GITHUB_OUTPUT"
        env:
          FLAKE_URI: "github:${{ github.event.pull_request.base.repo.full_name }}?rev=${{ github.event.pull_request.base.sha }}"

      - name: Get head SHA derivation path
        id: head-drv
        if: steps.changed.outputs.only_lock_changed == 'true'
        run: |
          set -o pipefail
          echo -n "path=" >>"$GITHUB_OUTPUT"
          nix eval --raw --file ./all-packages.nix | tee -a "$GITHUB_OUTPUT"
        env:
          FLAKE_URI: "github:${{ github.event.pull_request.head.repo.full_name }}?rev=${{ github.event.pull_request.head.sha }}"

      - name: Compare head and base derivation paths
        if: steps.changed.outputs.only_lock_changed == 'true' && steps.base-drv.outputs.path == steps.head-drv.outputs.path
        run: |
          echo "::error file=flake.lock::flake.lock changes produced the same derivation output"
          exit 1
